allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

catalog:
  "@biomejs/biome": 2.4.16
  knip: 6.14.2
  wrangler: 4.95.0

catalogMode: strict

managePackageManagerVersions: true

useNodeVersion: 25.9.0
