compatibility_date = "2022-01-01"

name = "ymkz"
type = "javascript"
workers_dev = false

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./main.mjs"

[miniflare]
host = "localhost"
port = 3000
