name: ci

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo
  DO_NOT_TRACK: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2
      - run: pnpm --version
      - run: node --version
      - run: pnpm run lint
      - run: pnpm run analyze
