name: deploy

on:
  push:
    branches: ['main']

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=VERSION::$(cat .node-version)"
        id: node-version
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.VERSION }}
          cache: npm
      - run: npm ci
      - uses: cloudflare/wrangler-action@1.3.0
        env:
          NODE_ENV: production
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
