name: pull-request
on:
  pull_request:
permissions:
  contents: read
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run build
