name: pull-request
on:
  pull_request:
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@2.0.1
        with:
          version: 6.11.5
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@2.0.1
        with:
          version: 6.11.5
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
